import ChapterTabs from "@/components/chapter-tabs";
import PanelHeading from "@/components/panel-heading";
import ScrollReveal from "@/components/scroll-reveal";

/** Centred body copy, matching the Solution panels. */
function Copy({
  children,
  delayClassName = "delay-1",
  className = "mt-6",
}: {
  children: React.ReactNode;
  delayClassName?: string;
  className?: string;
}) {
  return (
    <ScrollReveal className={className} delayClassName={delayClassName}>
      <p className="type-body mx-auto max-w-4xl text-center text-slate-700">{children}</p>
    </ScrollReveal>
  );
}

function OverviewPanel() {
  return (
    <>
      <PanelHeading>Technology Overview: Electromagnetic Energy-Flux Reactor</PanelHeading>

      <Copy className="mt-8">
        EER-SPG harnesses the power of electrons through electromagnetism, one of the four fundamental
        forces of nature. At the centre of the system is the main electromagnetic reactor. The reactor uses
        a primary excitation circuit and two secondary output circuits to generate electrical energy through
        electromagnetic induction.
      </Copy>
      <Copy delayClassName="delay-2">
        The system is anchored on Faraday&apos;s Law of Induction and the management of back electromotive
        force, or BEMF, generated by load current on the two secondary circuits. Through mutual flux
        cancellation, EER-SPG is designed to prevent secondary mutual coupling from increasing the primary
        excitation burden under load. This is the core technical principle behind GEMCOR&apos;s clean
        baseload generation platform.
      </Copy>
    </>
  );
}

function CoreMechanismPanel() {
  return (
    <>
      <PanelHeading>Core Operating Mechanism</PanelHeading>

      <Copy className="mt-8">
        The EER-SPG uses an electromagnetic reactor with two secondary circuits or outputs.
      </Copy>
      <Copy>
        When the primary circuit is excited, varying electromagnetism is generated in the electromagnetic
        core. This induces voltage in the two secondary circuits.
      </Copy>
      <Copy delayClassName="delay-2">
        As electrical load is connected, load current generates two distinct magnetic fields in the
        secondary circuits. These magnetic fields cancel the mutual flux that would otherwise link back to
        the primary circuit.
      </Copy>
      <Copy delayClassName="delay-2">
        With secondary mutual coupling cancelled, the main EM Reactor magnetic circuit input or excitation
        power remains constant at any given secondary output loading, provided the two output circuits share
        the same power factor and equal load.
      </Copy>

      <ScrollReveal className="mt-10" delayClassName="delay-2">
        <p className="type-emphasis mx-auto max-w-4xl text-center font-semibold text-[#0a745f]">
          This allows EER-SPG to operate as a fully regenerative baseload energy source on demand.
        </p>
      </ScrollReveal>
    </>
  );
}

function FluxCancellationPanel() {
  return (
    <>
      <PanelHeading>Magnetic Flux Cancellation</PanelHeading>

      <Copy className="mt-8">
        Mutual flux cancellation is the defining mechanism of EER-SPG.
      </Copy>
      <Copy>
        In a conventional electromagnetic system, secondary load current can induce a mutual flux that
        magnetically couples into the primary circuit. This mutual flux coupling by the secondary circuit
        increases the input burden of the primary circuit as secondary load current increases.
      </Copy>

      <ScrollReveal className="mt-8" delayClassName="delay-2">
        <p className="type-emphasis mx-auto max-w-4xl text-center font-semibold text-[#0a745f]">
          EER-SPG is designed differently.
        </p>
      </ScrollReveal>

      <Copy className="mt-8" delayClassName="delay-2">
        The two secondary circuits generate distinct magnetic fields that effectively cancel the mutual flux
        that should couple into the primary circuits generated by the currents of the secondary loads. The
        mutual flux cancellation effectively prevents the secondary current from coupling back into the
        primary excitation circuit.
      </Copy>
      <Copy delayClassName="delay-2">
        As load current intensifies, the magnetic fields on the two secondary coils also intensify,
        continuing the cancellation effect during loaded operation.
      </Copy>
    </>
  );
}

function ExcitationPanel() {
  return (
    <>
      <PanelHeading>Excitation-Only Input</PanelHeading>

      <Copy className="mt-8">
        EER-SPG{" "}
        <span className="font-semibold text-[#0a745f]">does not require fuel or feedstock</span> to generate
        electricity.
      </Copy>
      <Copy>It requires only a small amount of external excitation AC source to initiate operation.</Copy>
      <Copy delayClassName="delay-2">
        This excitation energises the primary circuit of the main EM reactor and creates varying forces of
        electromagnetism in the electromagnetic core.
      </Copy>

      <ScrollReveal className="mt-8" delayClassName="delay-2">
        <p className="type-body mx-auto max-w-4xl text-center font-semibold text-[var(--brand-dark)]">
          Initial excitation can be supplied by an energy storage battery, small solar installation, or wind
          power installation.
        </p>
      </ScrollReveal>

      <Copy className="mt-8" delayClassName="delay-2">
        After startup, the loop back inverter shifts the excitation source from the battery or other
        renewable sources to the main inverter output, allowing the battery to return to charging mode for
        future use or having the power generated by the renewable energy sources (use for initial
        excitation) seamlessly diverted and synchronise to the main output of the EER-SPG system.
      </Copy>
    </>
  );
}

const chapters = [
  { id: "tech-overview", label: "Overview", panel: <OverviewPanel /> },
  { id: "core-mechanism", label: "Core Mechanism", panel: <CoreMechanismPanel /> },
  { id: "flux-cancellation", label: "Flux Cancellation", panel: <FluxCancellationPanel /> },
  { id: "excitation-input", label: "Excitation Input", panel: <ExcitationPanel /> },
];

/** "Technology" — the four reactor chapters, tabbed. Our System only. */
export default function TechnologySection({ trailingSpace = false }: { trailingSpace?: boolean }) {
  return (
    <ChapterTabs
      id="technology"
      kicker="Technology"
      ariaLabel="The EER-SPG technology"
      chapters={chapters}
      overlapPrevious
      trailingSpace={trailingSpace}
    />
  );
}
